export const TOP_US_STOCKS = [
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Technology' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.', sector: 'Financial' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financial' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financial' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Defensive' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financial' },
  { symbol: 'PG', name: 'Procter & Gamble Co.', sector: 'Consumer Defensive' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', sector: 'Healthcare' },
  { symbol: 'HD', name: 'The Home Depot Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Defensive' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.', sector: 'Consumer Defensive' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Defensive' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare' },
  { symbol: 'MCD', name: "McDonald's Corporation", sector: 'Consumer Cyclical' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Technology' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare' },
  { symbol: 'NKE', name: 'NIKE Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Financial' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.', sector: 'Utilities' },
  { symbol: 'PM', name: 'Philip Morris Intl Inc.', sector: 'Consumer Defensive' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrials' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology' },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication Services' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', sector: 'Technology' },
  { symbol: 'IBM', name: 'IBM Corporation', sector: 'Technology' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer Cyclical' },
  { symbol: 'GS', name: 'The Goldman Sachs Group', sector: 'Financial' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Technology' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials' },
  { symbol: 'BA', name: 'The Boeing Company', sector: 'Industrials' },
  { symbol: 'GE', name: 'General Electric Company', sector: 'Industrials' },
  { symbol: 'HON', name: 'Honeywell International', sector: 'Industrials' },
  { symbol: 'UNP', name: 'Union Pacific Corp.', sector: 'Industrials' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrials' },
  { symbol: 'LOW', name: "Lowe's Companies Inc.", sector: 'Consumer Cyclical' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financial' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', sector: 'Technology' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'Healthcare' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financial' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrials' },
  { symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer Defensive' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Healthcare' },
  { symbol: 'ADP', name: 'Automatic Data Processing', sector: 'Technology' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Healthcare' },
  { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
  { symbol: 'MMM', name: '3M Company', sector: 'Industrials' },
  { symbol: 'TJX', name: 'The TJX Companies Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'MO', name: 'Altria Group Inc.', sector: 'Consumer Defensive' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Financial' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Healthcare' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Financial' },
  { symbol: 'BSX', name: 'Boston Scientific Corp.', sector: 'Healthcare' },
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', sector: 'Energy' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'SCHW', name: 'Charles Schwab Corp.', sector: 'Financial' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger Limited', sector: 'Energy' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', sector: 'Financial' },
  { symbol: 'MU', name: 'Micron Technology Inc.', sector: 'Technology' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology' },
  { symbol: 'MCHP', name: 'Microchip Technology', sector: 'Technology' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", sector: 'Consumer Cyclical' },
  { symbol: 'CDW', name: 'CDW Corporation', sector: 'Technology' },
  { symbol: 'MAR', name: 'Marriott Intl. Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Technology' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
];

export const SECTORS = [
  'Technology',
  'Financial',
  'Healthcare',
  'Consumer Cyclical',
  'Consumer Defensive',
  'Energy',
  'Industrials',
  'Communication Services',
  'Utilities',
  'Real Estate',
  'Basic Materials',
];

export function getTopStocks(count: number = 100): typeof TOP_US_STOCKS {
  return TOP_US_STOCKS.slice(0, count);
}